### ISSUE TITLE
New ESSD figures

### ISSUE THREAD

**Issue by bpbond** [bpbond/cosore#199]
Alexis Renchon offers this as a nice example, from Beringer et al. 2016:

![image](https://user-images.githubusercontent.com/1956468/78927593-26d8fc80-7a6d-11ea-9284-5090753892c8.png)

**Comment by stephpenn1** [comment]
**Other suggestions**

- Data counts against DOY (e.g., how well are 'non-growing seasons' covered) - because presumably one key application of this dataset would be to understand flux trends within a year (maybe even more so than over several years because many sites I assume have just a year of data).

- How much representation across terrestrial climate space (site MAT MAP plotted across a MAT MAP space; pretty sure I've seen this in one of your other papers). But this isn't as important as the last bullet because the strength of this dataset is coverage over time and not space

_figure 1:_
- can use the size of these "diamonds" to represent the # of data points at each site.

_figure 3:_
- Can we use shades of this blue color to show # of data points (or density of points per latitude band) for each year?

**Comment by bpbond** [comment]
From co-author Tarak El-Madany:
>I really like the waffle plot one of the best graphs to show which and how many ecosystems are covered in a given year.

**Comment by stephpenn1** [comment]
<img width="602" alt="Screen Shot 2020-04-15 at 5 18 33 PM" src="https://user-images.githubusercontent.com/20341158/79390126-26dd6e80-7f3d-11ea-89d1-c25802469964.png">

![image](https://user-images.githubusercontent.com/20341158/79385501-b16e9f80-7f36-11ea-8b1b-c7c4da713796.png)

![image](https://user-images.githubusercontent.com/20341158/79385353-710f2180-7f36-11ea-9e7d-6a4d0f12a189.png)

**Comment by avnimalhotra** [comment]
Wow, all three are great, but the DOY one is my favorite. Nice coverage across MAT too.

**Comment by bpbond** [comment]
Dang those DO look great. 👏   Nice job @stephpenn1 !

A couple suggestions: 
* In the MAT/MAP plot, the global distribution (grey dots) are overplotted, and we'd really like to see their distribution.  This could be solved by decreasing their alpha, or shifting to `geom_density2d`, or coloring (grey scale) by number of points in that degree bin, or ...?
* In the DOY plot, do we want one line for northern hemisphere, and one for southern?

**Comment by stephpenn1** [comment]
Thanks! Great suggestions, Ben. How about something like this? Also open to suggestions on the _type_ of geom to use here instead of a line. Unless you like the style as is

![image](https://user-images.githubusercontent.com/20341158/79523800-efe68600-802c-11ea-9ac3-c2d21177c3e6.png)

**Comment by bpbond** [comment]
Nice! That's _really_ informative. I think line is fine for now. Let's have the Y access say "Number of observations" please, but otherwise, looks great.
